name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas datetime tabulate
      - name: execute py script # run the run.py to get the latest data
        run: |
          python test.py

      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      # Runs a set of commands using the runners shell
      - name: Update README.md
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated report"
          git push
